# https://supabase.com/docs/guides/local-development/cli/config
project_id = "fti-supply-chain"

[api]
enabled = true

[db]
major_version = 17

[auth.hook.before_user_created]
enabled = true
uri = "pg-functions://postgres/public/hook_restrict_signup_to_fti_domain"
